title: 6738 Excalibur
description: Website for FRC team 6738 Excalibur
markdown: GFM
syntax_highlighter: rouge

exclude: [
    clean.sh ,
    .vscode/ ,
    .idea/ ,
    Gemfile ,
    Gemfile.lock ,
    jekyll-run.bat
]